sebinside/CraftBlock

- scripts/vanilla.zs
Disable Vanilla Tools using CT. Tested and working.
> Disable Vanilla Tools

- config/splash.properties
- scripts/vanilla.zs
habs sogar getestet lel wenns net geht dann liegts net an mir. hab sogar nen zweiten shift tooltip wenn dir der erste net gefällt.
> Added Vanilla Tooltips

- scripts/harvestcraft.zs
- scripts/hearthwell.zs
man muss hier echt mal bisschen aufräumen
> cleaned up code

- scripts/harvestcraft.zs
A cleaner approach for #13.
Tested and works well:
> Fix #12 - Improve harvestcraft cycle

- README.md
You missed AIOT Botania in upcoming mods. Fixed it, it's in the list now.
> Fix missing mod in upcoming mods

- README.md
- Moved Refined Storage to Größere Content-Mods
- Added MoreTweaker to Utility-Mods
- Added Initial Inventory to Utility-Mods
> Fixed Modlist

- README.md
- scripts/_drops.zs
Requres the following mods: 
- https://www.curseforge.com/minecraft/mc-mods/dropt
- https://www.curseforge.com/minecraft/mc-mods/athenaeum
> Add bonemeal leave drops

- advancements/assets/craftblock_advancements/advancements/workbench.json
Computer scientists and developers turn on and off, engineers don't need to.
[![grafik](https://user-images.githubusercontent.com/17405009/127379859-283b31d1-b7dc-48cb-963f-beac04fe2fc1.png)](https://www.youtube.com/watch?v=rp8hvyjZWHs)
> Trust me I'm an engineer.

- scripts/vanilla.zs
I'm sorry, but here is the fix. Thanks @voruti for spotting.
> Fix my git pfusch from sebinside#56

- config/astralsorcery.cfg
- scripts/astral.zs
Close #63, Close #65
This PR packs up the changes from those Pull Request and resolves the merge conflicts so you can easily merge both of them if desired.
> Astral Sorcery rebalanced

- scripts/immersive.zs
> Add Advanced Crafting Recipe for Blast Furnance

- scripts/vanilla.zs
Added Enchatment Table recipe idea from my mod suggestions #84 to the vanilla.zs script file.
New (harder) recipe for the Enchantment Table:
> Added harder recipe for Enchantment Table to vanilla.zs

- scripts/botania.zs
- scripts/vanilla.zs
See #82, unfortunately renaming the branch closed the PR.
> Add hints for wooden bowl & blaze powder

- scripts/extended.zs
> Advanced Handheld Crafting

- scripts/immersive.zs
Requires [Storage Drawers KAPPA Addon](https://www.curseforge.com/minecraft/mc-mods/storagedrawerskappa) (#111)
> Require treated wood drawer for Engineers Workbench

- scripts/vanilla.zs
> New coarse dirt recipe

- config/immersiveengineering.cfg
> Custom immersive toolbox contents

- config/morphtool.cfg
- scripts/embers.zs
A simple upgrade to the Morphing Tool.
This adds the following features:
* You can now use the Morphing Tool (when transformed like the Tinker's Hammer) to craft plates
* More Tools are added for the Morphing Tool to accept
* OpenComputers Wrench (Scrench)
* StorageDrawer Keys
* Drawer Key
* Concealment Key
* Personal Key
* Quantify Key
> Morphing tool upgrade

- scripts/vanilla.zs
> New  pistons recipe

- scripts/eventHandlers.zs
> Remove Pebbles once and for all

- scripts/embers.zs
> Auto Breaker is now hardcore

- config/quark.cfg
- scripts/harvestcraft.zs
- scripts/harvestcraft_gardens.zs
- scripts/vanilla.zs
Closes #121.
<details>
<summary>Nerves a bunch of recipes for Harvestcraft.</summary>
</details>
<details>
<summary>Adds JEI hints, documenting from which garden a crop can be obtained.</summary>
</details>
Also re-enables right click harvesting of fruits which was unintentionally disabled by #52
> Harvestcraft

- resources/contenttweaker/blockstates/botanic_alloy_block.json
- resources/contenttweaker/blockstates/materials/botanic_alloy_molten.json
- resources/contenttweaker/blockstates/materials/elementium_molten.json
- resources/contenttweaker/blockstates/materials/gaia_spirit_molten.json
- resources/contenttweaker/blockstates/materials/terrasteel_molten.json
These files get auto generated by content tweaker and where not included in the original PR #109.
As they spam the unstaged changes and drive me nuts I just conveniently committed them to master.
> Add missing auto generated blockstates from #109

- scripts/botania.zs
Mana rune will not be consumed and output was doubled
> Cheaper corporea sparks
